### PR TITLE
State switch 

### PR DESCRIPTION
**Pull request by ktavabi**
Please review and use to reproduce images in #4

### CODE REVIEW

**Comment by larsoner** [comment]
Rerunning task and rest now, looks like it's going to take a while!

**Comment by larsoner** [comment]
Will open a follow-up PR with some minor commits/updates. Can you upload your `.h5` files to `kasga` or let me know where they live on bucephalus? Long story short, I ran 90% of the subjects using a set of *old* preprocessed data, but as long as the results still look the same (they should, preprocessing differences were minor) then I should be good to just use your files. I'll still `rsync` the latest preprocessed files in case I need to re-run at some point, but hopefully I won't need to!

**Comment by ktavabi** [comment]
`sftp://10.155.251.206//media/ktavabi/INDAR/data/ilabs/genz_resting` is where the sources are? Do you need an account?

**Comment by larsoner** [comment]
Synced with `rsync -a --partial --progress --prune-empty-dirs --include="genz*_*/" --include="genz*_*/source/" --include="genz*_*/source/*.h5" --exclude="*" kam:/media/ktavabi/INDAR/data/ilabs/genz_resting/ .`

**Comment by ktavabi** [comment]
> (I aliased your machine as `kam` in my `.ssh/config`)

(how did you do that?)

**Comment by larsoner** [comment]
Here are the relevant lines:
```
Host kam
  HostName bucephalus.ilabs.uw.edu
  User ktavabi
```
See for example https://linuxize.com/post/using-the-ssh-config-file/

**Pull request merged**
